---
- name: Update apt caches
  become: yes
  apt:
    upgrade: "yes"
    update_cache: yes
    autoremove: yes
    autoclean: yes
    cache_valid_time: 86400 #One day

- name: Apt - install packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: latest
  loop:
    - build-essential
    - python3
    - python3-pip
    - ffmpeg
    - libavcodec-dev
    - libavformat-dev
    - libavutil-dev
    - libswscale-dev
    - libopencv-dev
    - libopencv-imgproc-dev
    - libopencv-imgcodecs-dev
    - libopencv-videoio-dev
    - uwsgi
    - uwsgi-plugin-python3
    - certbot
    - python3-certbot-nginx

- name: Pip install flask
  pip:
    name: flask
  become: yes

- name: GIT clone netDPr github repo.
  git:
    repo: "{{ git_repo }}"
    dest: /srv/{{ project_name}}
    depth: "1"
    force: yes
  become: yes


- name: Make install some things
  make:
    chdir: /srv/{{ project_name }}
    target: install
  become: yes
  notify:
    - restart_netdpr
    - restart_nginx

- name: create /etc/uwsgi
  become: true
  file:
    path: /etc/uwsgi
    state: directory

- name: create /etc/vassals
  become: true
  file:
    path: /etc/uwsgi/vassals
    state: directory

- name: link .ini to /etc/uwsgi/vassals
  become: true
  file:
    src: /etc/nginx/uwsgi.ini
    dest: /etc/uwsgi/vassals/{{ project_name }}.ini
    state: link

- name: setup logz at /var/log/uwsgi/
  become: true
  file:
    path: /var/log/uwsgi/
    state: directory

- name: create  logfile for uwsgi
  become: true
  file:
    path: /var/log/uwsgi/{{ project_name }}.log
    state: touch
    mode: 0775
    owner: '{{ webapp_user }}'
    group: '{{ webapp_user }}'

- name: create /run/uwsgi directory for sockets?
  become: true
  file:
    path: /run/uwsgi
    state: directory
    owner: '{{ webapp_user }}'
    group: '{{ webapp_user }}'
    mode: 0760

- name: setup uwsgi service to launch at startup.
  become: true
  template:
    src: ../templates/emperor.uwsgi.service
    owner: root
    group: root
    dest: /etc/systemd/system/emperor.uwsgi.service

- name: enable uwsgi service
  become: true
  service:
    name: emperor.uwsgi
    enabled: yes

- name: reload daemons
  become: true
  service:
    name: emperor.uwsgi
    daemon_reload: true

- name: start uwsgi service
  become: true
  service:
    name: emperor.uwsgi
    state: started


- name: ufw allow http
  become: yes
  ufw:
    rule: allow
    src: any
    port: http
    proto: tcp

- name: ufw allow https
  become: yes
  ufw:
    rule: allow
    src: any
    port: https
    proto: tcp

- name: Certbot it up.
  become: yes
  command: certbot --nginx -d diyrot.epss.ucla.edu --non-interactive --redirect --agree-tos -m webmaster@epss.ucla.edu

- name: service check
  service:
    name: netdpr
    state: started
  become: yes

- name: service check
  service:
    name: nginx
    state: started
  become: yes
