---
- name: Update apt caches
  become: yes
  apt:
    upgrade: "yes"
    update_cache: yes
    autoremove: yes
    autoclean: yes
    cache_valid_time: 86400 #One day

- name: Apt - install packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: latest
  loop:
    - build-essential
    - python3
    - python3-pip
    - ffmpeg
    - libavcodec-dev
    - libavformat-dev
    - libavutil-dev
    - libswscale-dev
    - libopencv-dev
    - libopencv-imgproc-dev
    - libopencv-imgcodecs-dev
    - libopencv-videoio-dev
    - uwsgi
    - uwsgi-plugin-python3
    - certbot
    - python3-certbot-nginx

- name: Pip install flask
  pip:
    name: flask
  become: yes

- name: GIT clone netDPr github repo.
  git:
    repo: "{{ git_repo }}"
    dest: /srv/{{ project_name}}
    depth: "1"
    force: yes
  become: "yes"

- name: permissions!
  file:
    state: directory
    path: /srv/diyrot
    recurse: yes
    mode: 0770
    owner: epssadmin
    group: www-data
  become: yes

 

# - name: Make install some things
#   make:
#     chdir: /srv/{{ project_name }}
#     target: install
#   become: yes
#   notify:
#     - restart_netdpr
#     - restart_nginx
- name: NGINX - Creating nginx conf
  become: true
  template:
    src: ../templates/nginx-conf.j2
    dest: /etc/nginx/sites-available/{{ project_name }}.conf
    owner: root
    mode: 0644

- name: link to active 
  become: yes
  file:
    state: link
    src: /etc/nginx/sites-available/{{ project_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ project_name }}.conf

    
- name: create /etc/uwsgi
  become: true
  file:
    path: /etc/uwsgi
    state: directory

- name: create /etc/vassals
  become: true
  file:
    path: /etc/uwsgi/vassals
    state: directory


- name: Replace a localhost entry with our own
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: 127.0.0.1 localhost
    owner: root
    group: root
    mode: '0644'

- name: link .ini to /etc/uwsgi/vassals
  become: yes
  template:
    src: ../templates/diyrot.ini
    dest: /etc/uwsgi/vassals/{{ project_name }}.ini
    owner: "{{ webapp_user}}"
    group: "{{ webapp_user}}"

- name: setup logz at /var/log/uwsgi/
  become: true
  file:
    path: /var/log/uwsgi/
    state: directory

- name: create  logfile for uwsgi
  become: true
  file:
    path: /var/log/uwsgi/{{ project_name }}.log
    state: touch
    mode: 0775
    owner: '{{ webapp_user }}'
    group: '{{ webapp_user }}'

- name: create /run/uwsgi directory for sockets?
  become: true
  file:
    path: /run/uwsgi
    state: directory
    owner: '{{ webapp_user }}'
    group: '{{ webapp_user }}'
    mode: 0760

- name: setup uwsgi service to launch at startup.
  become: true
  template:
    src: ../templates/emperor.uwsgi.service
    owner: root
    group: root
    dest: /etc/systemd/system/emperor.uwsgi.service

- name: enable uwsgi service
  become: true
  service:
    name: emperor.uwsgi
    enabled: yes

- name: reload daemons
  become: true
  service:
    name: emperor.uwsgi
    daemon_reload: true

- name: start uwsgi service
  become: true
  service:
    name: emperor.uwsgi
    state: started


- name: ufw allow http
  become: yes
  ufw:
    rule: allow
    src: any
    port: http
    proto: tcp

- name: ufw allow https
  become: yes
  ufw:
    rule: allow
    src: any
    port: https
    proto: tcp

- name: Certbot it up.
  become: yes
  command: certbot --nginx -d diyrot.epss.ucla.edu --non-interactive --redirect --agree-tos -m webmaster@epss.ucla.edu

- name: service check
  service:
    name: nginx
    state: started
  become: yes
